dist: bionic
language: rust
rust: 
    - nightly

before_install:
    - wget https://raw.githubusercontent.com/creationix/nvm/v0.34.0/nvm.sh -O ~/.nvm/nvm.sh
    - source ~/.nvm/nvm.sh
    - nvm install node
    - nvm use node
    - curl -u dakom:"$GITHUB_TOKEN" -s https://api.github.com/repos/WebAssembly/binaryen/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | xargs -I {} wget -c https://github.com/WebAssembly/binaryen/releases/latest/download/binaryen-{}-x86_64-linux.tar.gz -O binaryen.tgz
    - mkdir binaryen && tar -zxvf ./binaryen.tgz -C binaryen --strip-components 1
    - export PATH=./binaryen:$PATH
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-bindgen-cli

install:
    - npm ci
    - wasm-opt --help

script:
    - cd src/crates/core
    - cargo test
    - cd ../renderer
    - cargo test 
    - cd ../..
  
after_success:
    - npm run bundle:ci
    - cp -R _static/* dist/

deploy:
    local_dir: dist
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master
